### ISSUE TITLE
question: hier::VariableDatabase reset

### ISSUE THREAD

**Issue by Dekken** [LLNL/SAMRAI#104]
Hi there, 

can you tell me if it's possible to reset the VariableDatabase singleton within a single binary execution?

I was hoping the tbox::SamraiManager shutdown business would do it but it doesn't seem to.

Thanks

**Comment by maikel** [comment]
Do you have a reproducer? From my understanding  [`VariableDatabase::shutdownCallback()`](https://github.com/LLNL/SAMRAI/blob/2879555a0bedc7fd8d22467dcb3a503b98729796/source/SAMRAI/hier/VariableDatabase.C#L52) should do the job.

**Comment by Dekken** [comment]
I saw that function but I've no idea how to use it.

Do you have an example of a "reproducer" or does it involve the StartupShutdownManager?

**Comment by maikel** [comment]
What I mean is, that calling `SAMRAI::tbox::SAMRAIManager::shutdown()` should safely delete your `SAMRAI::hier::VariableDatabase`. You claim it does not. Can you do a small example where it does not work?

**Comment by Dekken** [comment]
I got it working with the following 

```

#include <SAMRAI/tbox/SAMRAIManager.h>
#include <SAMRAI/hier/VariableDatabase.h>

void a(int argc, char* argv[]){

  SAMRAI::hier::VariableDatabase *db = nullptr;

  SAMRAI::tbox::SAMRAIManager::startup();
  db = SAMRAI::hier::VariableDatabase::getDatabase();
  db->printClassData();

  SAMRAI::tbox::SAMRAIManager::shutdown();

  // db->printClassData(); // segfaults as it should
}


int main(int argc, char* argv[]){

  SAMRAI::tbox::SAMRAI_MPI::init(&argc, &argv);
  SAMRAI::tbox::SAMRAIManager::initialize();

  a(argc, argv);
  a(argc, argv);

  SAMRAI::tbox::SAMRAIManager::finalize();
  SAMRAI::tbox::SAMRAI_MPI::finalize();

  return 0;
}
```

thanks for your help
