### ISSUE TITLE
hier::VariableDatabase pybind11 segfault

### ISSUE THREAD

**Issue by Dekken** [LLNL/SAMRAI#105]
Hi there,

While trying to write a python wrapper for some of our code I noticed a spurious segfault when trying to initialize the VariableDatabase via python.

I've put together a minimal reproduction environment here: 
https://github.com/Dekken/samrai_pybind11

The segfault doesn't make a lot of sense to me but it may to you?

Thanks

**Comment by maikel** [comment]
I think you need to initialize SAMRAI.

**Comment by Dekken** [comment]
fair point, will give that a go

**Comment by Dekken** [comment]
solved thanks
