### ISSUE TITLE
-DHDF5_DIR option does not work

### ISSUE THREAD

**Issue by borjaMinano** [LLNL/SAMRAI#134]
Trying to use a custom hdf5 installation using cmake parameter -DHDF5_DIR does not work.
The configuration system ignores that option. In fact, a quick grep search in the scripts shows no result of HDF5_DIR variable usage.

Could it be a mistake in the cmake files?

**Comment by borjaMinano** [comment]
Using -DHDF5_C_COMPILER_EXECUTABLE works, now it configures the correct hdf5. 

Now the problem is compiling. Despite SILO is recognized with -DSILO_DIR flag and SILO_INCLUDE_DIRS:PATH and SILO_LIBRARIES:FILEPATH are correctly set, the compiler process cannot find silo.h.

I took a look at the code and it seems CXX_INCLUDES does not have silo include path, so "Building CXX object source/SAMRAI/tbox/CMakeFiles/SAMRAI_tbox.dir/SiloDatabase.C.o" fails.

Now my configuration command is: cmake .. -DHDF5_DIR=/opt/hdf5 -DSILO_DIR=/opt/silo -DHDF5_C_COMPILER_EXECUTABLE=/opt/hdf5/bin/h5cc -DENABLE_SILO=ON

**Comment by nselliott** [comment]
I apologize for this.  I found a bug in one of the CMakeLists files in the setting of the SILO dependency.  We will need to make a bugfix release, but until then the fix is available in the branch` bugfix/nselliott/silo-cmake`.  The file `source/SAMRAI/tbox/CMakeLists.txt` is the only one changed.

**Comment by borjaMinano** [comment]
Thank you very much. Now it compiles correctly.
