### ISSUE TITLE
Failed assertion: pd_new->getTime() >= s_time

### ISSUE THREAD

**Issue by nicolasaunai** [LLNL/SAMRAI#135]
```
P=0000000:Program abort called in file 
SAMRAI/source/SAMRAI/xfer/RefineTimeTransaction.C'' at line 268
P=0000000:ERROR MESSAGE: 
P=0000000:Failed assertion: pd_new->getTime() >= s_time
```

I don't understand what happens.
I have a hierarchy with 2 patches (0 and 1) on level 0, 1 patch on level 1.
I get this error while calling a schedule to fill ghosts on one of the level 1 patchdata.

The weird thing is that when calling schedule->fillData(), I see that the coarse patchData that is the source at new time has timeStamp 0.001 as it was set and so as it should be. 

However, in the second pass in recursiveFill I see the timeStamp of the patchdata is 0.

Any idea what could mess with that value?

**Comment by nicolasaunai** [comment]
That's what I get when looking at the hierarchy before schedule->fillData() gets called to fill ghosts on level1 patchdata. I'm using time interpolator with recursive time stepping

![image](https://user-images.githubusercontent.com/3200931/84439469-8e135880-ac38-11ea-8a33-8ef3a6f0dbaf.png)

Timestamp is 0.001, which corresponds to the time reached by level 0 at the end of its first time step.


Then, during the fillData(), I see two calls to recursiveFill(), and in the second I get : 

![image](https://user-images.githubusercontent.com/3200931/84440076-a9329800-ac39-11ea-99d1-b1d6129fb33c.png)

I guess the d_src_level.d_level_number is 0, which is OK, there are two patches, which is OK, but all of their patchdata (including the one of interest for the schedule (ID=3)) have their timeStamp 0.

So something must happen to put them to 0.

**Comment by nselliott** [comment]
I will try to figure this out.  Are you using one of SAMRAI's PatchData classes provided in the pdat directory or is it a derived type in your application?

**Comment by nicolasaunai** [comment]
We're using our own derived PatchData:
https://github.com/nicolasaunai/PHARE/tree/initparticles/src/amr/data/field

Actually we have two ways to start our simulation. The first consists in running the executable. The second consists in calling python wrappers (made with pybind11) of our high-level components, from a python interpreter. 

In the first case all seems OK. I see the timestamp having the right value and the simulation runs ok. In the second case I got the problem described above at the very first attempt to refine data onto level 1 with time interp. Both ways should be strictly identical.

 What I can't figure out is that in the python case, the timestamp seems fine and something becomes funky after entering in the SAMRAI part.

I get this behavior on a mac.

**Comment by nicolasaunai** [comment]
ok bug solved. Was actually on our side we initialized the hierarchy twice without knowing... which resulted somehow advancing levels that were not the one shared with the schedule.... hence timestamp staying 0 (and not being overwritten).

**Comment by nselliott** [comment]
I'm glad you figured it out.
