### ISSUE TITLE
C++ file extension 

### ISSUE THREAD

**Issue by jeandet** [LLNL/SAMRAI#144]
Hello, 

Would a PR renaming all files from .C to .cpp be accepted? This would allow to write Meson Wrap and use SAMRAI as Meson dependency. And that would also make SAMRAI use a more common file extension for C++.

**Comment by nselliott** [comment]
This is worth discussing, but we would need to make this change on our own timeline, so we won't immediately accept an external pull request that does this.

**Comment by jeandet** [comment]
OK, thank you for your quick answer. This change would be really nice. I can make a PR when you want, you can ping me when/if you are ready.

**Comment by rhornung67** [comment]
Should change header files from *.h to *.hpp at the same time as well.

**Comment by jeandet** [comment]
@rhornung67 , Changing .C to .cpp should have no visible effect on users while changing headers extension from .h to .hpp force them to change their code. Are you sure you want this? The only benefit I see with using .hpp is that it might avoid some tooling wrongly assuming .h as C language instead of C++.

**Comment by PhilipDeegan** [comment]
I just checked and the following appears to work 

```
find source -type f -exec sed -i -e 's/\.C/\.cpp/g' {} \;
find source -name '*.C' -exec sh -c 'mv "$0" "${0%.C}.cpp"' {} \;
find source -type f -exec sed -i -e 's/cppomm_dup/Comm_dup/g' {} \;
find source -type f -exec sed -i -e 's/cppomm_rank/Comm_rank/g' {} \;
find source -type f -exec sed -i -e 's/cppomm_size/Comm_size/g' {} \;
```

**Comment by PhilipDeegan** [comment]
@nselliott any chance we can get an update on this?

**Comment by nselliott** [comment]
The change to .cpp will be coming probably around the beginning of the year.
