### ISSUE TITLE
scratch source and dest IDs

### ISSUE THREAD

**Issue by nicolasaunai** [LLNL/SAMRAI#162]
Hi, 

In our application, we often set the source, dest and scratch IDs to the same value while calling registerRefine. And everything seems to run as I expect (the right data is copied/refined) at the expected location in the expected way).
 
However it looks wrong when reading the documentation of refineAlgorithm, which says : 

```
In general, the destination and scratch data components may be the same (assuming that the scratch component has a sufficient ghost cells width). The source and scratch components SHOULD NOT be the same, since the interiors of the source space could be changed by the use of the scratch data as temporary work space.
```

I am not sure I understand the reason why the source and scratch IDs should differ (and thus source and dest, since dest could be equal to scratch). 

What is the nature of "temporary processing" that is mentioned after source is copied into scratch ? At which point is it (or can it be) performed?

**Comment by nselliott** [comment]
Thanks for pointing this out--this documentation is outdated and incorrect.  It is fine in most cases to have all three IDs be the same, especially when using RefineSchedule for ordinary copies and refinement.  If you find that it is working in your code, there is no reason for you to change it.

There can be use cases where it is not advisable to do this, but these usually involve application-created operations on the data in places such as an implementation of RefinePatchStrategy::postprocessRefine.  There could be examples where the computation requires separate data buffers for the source and scratch data.  However, this does not apply to more common modes of use of RefineSchedule and RefineAlgorithm.
