### ISSUE TITLE
Binary characters in output from TBOX_WARNING

### ISSUE THREAD

**Issue by PhilipDeegan** [LLNL/SAMRAI#163]
Hi, 

Is the use of "std::ends" possibly a typo?

As far as I can see it's causing binary null characters to appear in our logs, which is not ideal.

Reference: https://github.com/LLNL/SAMRAI/blob/5bcd22908d1857b257cceaf3d80475a7a32a6c59/source/SAMRAI/tbox/Utilities.h#L67

**Comment by nselliott** [comment]
It is not a typo, but it is something we should remove.  It's left over from when `std::ostrstream` was used, and `std::ends` was needed to add the null terminator character to the `char*` C-strings.  That is no longer necessary when using `std::ostringstream` and `std::string` and it can cause unwanted `\0` characters in the strings, so we will remove it.  Thank you for the report.
