### ISSUE TITLE
"m4: command not found" issue in any ubuntu:18.04 or centos 8 docker image

### ISSUE THREAD

**Issue by ctian282** [LLNL/SAMRAI#174]
I was trying to compile SAMRAI with docker. Within any ubuntu:18.04 docker container, for example I used 
```
docker pull rectaflex/cosmo-universal:gcc
```
with command 
```
cmake .. 
```
then 
```
make 
```
it shows error
```
/bin/sh: 1: m4: not found
source/SAMRAI/pdat/CMakeFiles/SAMRAI_pdat.dir/build.make:73: recipe for target 'source/SAMRAI/pdat/fortran/pdat_concoarsen1d.f' failed
make[2]: *** [source/SAMRAI/pdat/fortran/pdat_concoarsen1d.f] Error 127
make[2]: *** Deleting file 'source/SAMRAI/pdat/fortran/pdat_concoarsen1d.f'
make[2]: *** Waiting for unfinished jobs....
``` 
when compiling proceeds to around 22%, and when it is compiling pdat components. Use a different ubuntu image or cents8 image will not solve this problem unless switch to a ubuntu:20.04.

**Comment by davidbeckingsale** [comment]
You need to install the [m4](https://www.gnu.org/software/m4/) tool in your Docker container. SAMRAI uses m4 to generate some Fortran files.

**Comment by ctian282** [comment]
Yes, that solves the issue, thanks.
