### ISSUE TITLE
std::iterator deprecated in C++17 - error with -Werror with gcc 13.2.1

### ISSUE THREAD

**Issue by nicolasaunai** [LLNL/SAMRAI#238]
this code here:
https://github.com/LLNL/SAMRAI/blob/11612bcb456baf7a245376462438882505f14b9e/source/SAMRAI/hier/Box.h#L1472

leads to 

`error: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Werror=deprecated-declarations]` with gcc 13.2.1 (fedora 38)

See for instance [this blog post](https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/)

**Comment by nicolasaunai** [comment]
I also see that on gcc 12.3.1 actually, -Werror=deprecated-declarations

**Comment by rhornung67** [comment]
Hopefully this is helpful: https://stackoverflow.com/questions/43268146/why-is-stditerator-deprecated

**Comment by PhilipDeegan** [comment]
This is done and can be closed
