### ISSUE TITLE
 warning: 'sprintf' is deprecated on OSX

### ISSUE THREAD

**Issue by PhilipDeegan** [LLNL/SAMRAI#245]
```
SAMRAI/tbox/Utilities.cpp:54:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
      sprintf(path_buf, "%s", path.c_str());
```

I had this issue before with SWIG on OSX: 
reference: https://github.com/swig/swig/issues/2502

I'm not sure if this is real issue or just something Apple has decreed. 
If you don't intend to do anything because OSX(or similar) are not supported feel free to close this.

**Comment by nselliott** [comment]
This was a small enough change that I went ahead and did it #248
