### ISSUE TITLE
“Make clean” deletes files needed for compilation

### ISSUE THREAD

**Issue by JacobCrabill** [LLNL/SAMRAI#34]
I had to try a few times to get all my paths setup, and in the process used “make clean” a few times, only to discover that it deleted several important files, primarily:

appu/fortran/appu_cpdat2buf2d.f
And
appu/fortran/appu_cpdat2buf3d.f

A few .f and .C files from the source/test directory were also deleted.  My fix was simply to to a git reset & git pull.

**Comment by davidbeckingsale** [comment]
Did this happen on the `master` branch?

**Comment by JacobCrabill** [comment]
Yes, on the master branch using the latest commit from a few days ago.  I didn't look into the 'clean' target in the makefile(s), but I'm assuming that, since other *.f files in the appu folder are auto-generated from *.m4 files, the 'clean' target just removes all *.f files from that folder.

**Comment by davidbeckingsale** [comment]
Thanks for reporting this - checkout #35

**Comment by JacobCrabill** [comment]
Looks correct; thanks!
