### ISSUE TITLE
Disable Tests in CMake (blt feature branch)

### ISSUE THREAD

**Issue by maikel** [LLNL/SAMRAI#60]
There is a CMake option called `ENABLE_TESTS` but IIUC it is being ignored. I.e. `source/test` will always be added as a subdirectory to the project. It would be nice to include it conditionally only. Thoughts on that? I can provide a PR.

**Comment by davidbeckingsale** [comment]
Yup, we should have that! Feel free to provide a PR if you need it urgently, otherwise we'll add it to our TODO list 😄

**Comment by davidbeckingsale** [comment]
Closed by #61
