### ISSUE TITLE
gcc 7.1.0 error

### ISSUE THREAD

**Issue by rw-anderson** [LLNL/SAMRAI#7]
source/SAMRAI/pdat/OuternodeData.C, line 196 gives error in gcc 7.1.0

**Comment by rw-anderson** [comment]
Fix awaiting push out to github, will mark closed at that point.

**Comment by BryanFlynt** [comment]
Not sure why other compiler let this slide.  Here is the fix:

Replace (old line 196):
for (int d = getDim() - 1; d >= 0; --d) {

With (new line 196):
for (int d = getDim().getValue() - 1; d >= 0; --d) {

**Comment by davidbeckingsale** [comment]
Fixed now pushed.
